### ISSUE TITLE
Settings : The current group appears in 'available' devices

### ISSUE THREAD

**Issue by AdyRock** [hive/com.groups#14]
Using Alpha 2.1.507. Got the app configuration and select s group. 
I see the group I am editing in the list. Would that cause a problem if I added the group to the group?

**Comment by hive** [comment]
I would say that there is a very good chance that something bad would happen.

**Comment by hive** [comment]
Ive removed the 'current' item from the device list - 

BUT it is still possible to cause an infinate loop, as I made it so that you could add other groups to a group. So technically you could : 

GroupA ( with GroupB in it) -> GroupB (with GroupA in it) .

I'm considering removing the ability of adding a group to a group to stop users making a mistake in the app. But I personally use this feature all over the place : temperature, smoke alarms, contact sensors, alarms - etc. 

ie for lights

All Downstairs lights has  ( 'all kitchen lights',  'all dining room lights ', 'all living room lights', 'etc')
All Upstairs lights has (all bedroom lights,  all bathroom lights, etc etc)
All lights has all Downstairs lights + all Upstairs lights. 

What do you think?

**Comment by hive** [comment]
Not really as each of the groups is sandboxed during run time, So while a group may know that it has another group inside of it - it wont know what is inside that other group. 

I think the correct solution is to enable it an advance settings with a warning, however that is quite a bit of work for what may be an edge case. Ill monitor it and see if this issue comes up during beta testing of the settings.

**Comment by hive** [comment]
Ive created a new ticket for the new feature : 

https://github.com/hive/com.groups/issues/21


As this particular issue (group shows itself with in the devices) is now fixed, im going to close this ticket. we can continue to discuss additional features/fixes in the new ticket.

Thanks
