### ISSUE TITLE
Group with blinds

### ISSUE THREAD

**Issue by Mindsuk** [hive/com.groups#36]
Hi Jamie, I tried to use your App for my blinds. But some blinds don‘t open ore close! But not everytime the same 🤔
Could you please have a look?

By the way, the delay is bad too 😕

**Comment by hive** [comment]
Hi, 

The group app, doesn't actually send/receive any commands, it goes through all the devices in a group and tells them to do 'what they would normally do'. It sounds like 'what they normally would do' is the part which is failing. 

So, couple of questions : 

a) Do your blinds sometimes require that you press the button more then once  in order to go up/down. 

b) When you place all your blinds in a flow which moves them all up/down - do you encounter the same issue?

c) Do you encounter the same issue if each of the blinds in the flow has a different time delay on each blind? 

d) What type of blinds do you have?

Thanks

**Comment by hive** [comment]
@Mindsuk Any update?

**Comment by hive** [comment]
Hi @Mindsuk I am closing this issue and assuming that the problem has resolved itself, due to lack of information.

Please let me know if you have more information and ill open it up again.

Regards.
